plugins {
    id 'java'
    id 'application'
}

group = 'me.Lusik21556'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

application {
    mainClass = 'me.Lusik21556.skxobfuscator.Main'
}

jar {
    manifest {
        attributes 'Main-Class': 'me.Lusik21556.skxobfuscator.Main'
    }
    from {
        configurations.runtimeClasspath.collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
